// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuppkohfkcgjkixggupe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1cHBrb2hma2NnamtpeGdndXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDI4NjYsImV4cCI6MjA2Nzg3ODg2Nn0.rzIX3Z8fEZYPmX7FobjAWDbiO7mlsNMedMCBlDAb01E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});